### ISSUE TITLE
Please create a release

### ISSUE THREAD

**Issue by Sammyboy** [danfruehauf/incron#4]
Hi,
for an update of the SlackBuild for incron from version 0.5.10 to 0.6.0 we need a static release of that version.
Cloning or downloading of incon-master.tar.gz is not allowed for Slackbuilds, since that archive is generated dynamically from the current master branch and if there are changes in the master branch, then the SlackBuild might fail.

Thanks.

**Comment by danfruehauf** [comment]
So officially, this is not the "main" release of this project. There are a couple of forks.

I used http://inotify.aiken.cz/?section=incron and forked it at this stage in time because I believe that the current maintainer is not only unresponsive and does not steer the project in the right direction.

The official release can be found here:
https://github.com/ar-/incron

I'm more than happy to create a release if you'd like me to though.

**Comment by Sammyboy** [comment]
Yes, I know it's a fork, but your version works better for me than the original 0.5.12. Also there are a lot of open issues which the developer seems not to care about.
So if you create a release I'd rather take your version to SlackBuilds (if it will be accepted by the core team).

**Comment by danfruehauf** [comment]
> Also there are a lot of open issues which the developer seems not to care about.

That's kind of how I felt too.

So be in then. I'm happy to do a release.

To be honest with that project I started doing a few modifications and then kind of left it lying around. However if there's interest, I'll probably continue improving it.

**Comment by danfruehauf** [comment]
Tagged it as 0.6.0.

Please do open issues and I'll try to address them. Lets make this little tool awesome again.
